### ISSUE TITLE
Ugly ass description section

### ISSUE THREAD

**Issue by paulirish** [Modernizr/modernizr-ui#7]
dis shit:

![image](https://cloud.githubusercontent.com/assets/39191/4040051/9ed13a18-2cda-11e4-9b34-76a346ba7fca.png)

**Comment by paulirish** [comment]
It's due to a [pretty greedy regex](https://github.com/Modernizr/Modernizr/blob/f45491c2da1ac925d68b1a08b5922188423bde60/lib/generate-meta.js#L20) that grabs text until the last `*/`

unfortunately we have a bunch of `/* jshint -W053 */`  in our detects that get caught up in this.

solutions:
- don't use flowerbox comments inside the code (not sure if jshint supports `//` for those)
- write a goddamn better regex

**Comment by SlexAxton** [comment]
fwiw, it _is_ commented: https://github.com/Modernizr/Modernizr/blob/f45491c2da1ac925d68b1a08b5922188423bde60/lib/generate-meta.js#L17

**Comment by patrickkettner** [comment]
so like...[`\/\*\sDOC([\s\S]+?)\*\/`](https://www.debuggex.com/r/eblTtxaFeib-ApDJ/0)?

([current for comparision](https://www.debuggex.com/r/FIXEShuVAele0htl/0))

**Comment by patrickkettner** [comment]
also, fwiw, jshint does support `//`

**Comment by paulirish** [comment]
yaya thxxx
- went nongreedy on the regex; https://github.com/Modernizr/Modernizr/commit/f526d97579d7ab42031bb2b852e8551d7b9f87e2
- bumped our local metadata: https://github.com/Modernizr/modernizr-ui/commit/8569e9e1db9ead42f8d20adce04d3c648014f69e
